export default {
    'Link.Slogan': 'FewBox',
    'Link.Feature': 'Feature',
    'Link.Pricing': 'Pricing',
    'Link.Donate': '👍 Donate',
    'Link.Registry': 'Registry',
    'Label.More': 'More',
    'Label.FreeLicense': 'Free',
    'Label.MonthlyLicense': 'Monthly',
    'Label.YearlyLicense': 'Yearly',
    'Label.Copyright': 'COPYRIGHT © 2020 BY FEWBOX, ALL RIGHTS RESERVED',
    'Label.Brand': 'FewBox',
    'Label.Trusted': 'TRUSTED BY ©FEWBOX CLIENTS',
    'Label.Feature1Name': 'Feature 1',
    'Label.Feature1Description': 'The best feature from FewBox.',
    'Label.Feature2Name': 'Feature 2',
    'Label.Feature2Description': 'The best feature from FewBox.',
    'Label.Feature3Name': 'Feature 3',
    'Label.Feature3Description': 'The best feature from FewBox.',
    'Label.PricingTitle': 'Pricing',
    'Label.PricingDescription': 'The payment is processed by PayPal (Safeguard purchases). Any major credit card or debit card is supported, you don’t need a PayPal account to finish the order.',
    'Label.ProductTitle': 'Product',
    'Label.ProductDescription': 'We provide Smart, Simple products to our clients.',
    'Label.FeatureTitle': 'Features',
    'Label.FeatureDescription': 'We provide Smart, Simple products and Extentions to our clients.',
    'Label.TeamTitle': 'Teams',
    'Label.TeamDescription': 'WHO WE ARE',
    'Label.Purchase': 'Purchase',
    'Label.FreeLicenseUnit': '',
    'Label.MonthlyLicenseUnit': '/month',
    'Label.YearlyLicenseUnit': 'year'
}